from .register_payment import register_payment_by_resident
from .get_info_resident import get_all_info_resident
from .view_image_resident import view_image_of_resident
from .get_info_by_number_device import get_all_info_by_number_device
from .finish_package import send_message_for_finish_package
from .register_consumer import register_volume_and_fluxo